export const uiCopy = {
  nav: {
    commandCenter: "Command Center",
    robots: "Robots",
    compare: "Compare",
    radarFeed: "Radar Feed",
    news: "News",
    robotMatchmaker: "Robot Matchmaker",
  },
  navIcons: {
    commandCenter: "⌂",
    robots: "◉",
    compare: "✣",
    radarFeed: "◎",
    news: "✎",
    robotMatchmaker: "◈",
  },
  sidebar: {
    freshnessScore: "Data Freshness",
    lastSignal: "Last Signal",
  },
  homepage: {
    commandCenter: "Command Center",
    newsEyebrow: "News",
    latestRobotNews: "Latest Robot News",
    radarFeedEyebrow: "Radar Feed",
    latestRobotUpdates: "Latest Robot Updates",
    stayOnRadar: "Stay on Radar",
    viewFullProfile: "View Full Profile",
  },
  matrix: {
    showDiscontinued: "Show discontinued robots",
    showBuyNowOnly: "For sale only",
    windowEyebrow: "Matrix scan",
    prevWindow: "Prev scan",
    nextWindow: "Next scan",
    unitsRange: (start: number, end: number, total: number) =>
      `Units ${String(start).padStart(2, "0")}–${String(end).padStart(2, "0")} of ${total}`,
    windowLabel: (page: number, pageCount: number) =>
      `Scan ${String(page).padStart(2, "0")}/${String(pageCount).padStart(2, "0")}`,
  },
  robot: {
    tabs: {
      overview: "Overview",
      capabilities: "Capabilities",
      techSpecs: "Tech Specs",
      ecosystem: "Ecosystem",
      availability: "Availability",
      signalHistory: "Signal History",
      fieldReports: "Reviews",
    },
    trackRobot: "Track Robot",
    tracking: "Tracking",
    addToCompare: "Add to Compare",
    inCompare: "In Compare",
    relatedRobots: "Related Robots",
    robotSignals: "Robot Signals",
    news: "News",
  },
  scores: {
    readinessScore: "Readiness Score",
    readinessScoreHint:
      "How close this robot is to practical home use, based on specs, demos, and buy signals we track.",
    realityScore: "Reality Score",
    realityScoreHint:
      "How verified the robot is in the real world — shipping, pilots, and public proof.",
    marketStatus: "Market Status",
    freshnessScore: "Data Freshness",
    confidenceScore: "Confidence Score",
    lastSignal: "Last Signal",
  },
  comments: {
    submitLabel: "Post comment",
    submitFieldReport: "Submit Field Report",
    emptyPrompt: "Be the first to share a question or hands-on note.",
    usernamePlaceholder: "How should your name appear?",
  },
  updates: {
    pageTitle: "Robot Updates",
    readUpdate: "Read update",
    readStory: "Read story",
    viewAll: "View all",
    noUpdatesYet: "No updates yet.",
    noNewsYet: "No news yet.",
    noDataUpdatesForRobot: "No data updates for this robot.",
    noNewsForRobot: "No news for this robot.",
  },
  compare: {
    eyebrow: "Compare",
  },
  search: {
    ariaLabel: "Search robots, news, and radar feed",
    sectionNewsAndRadar: "News & Radar Feed",
    compareRobots: "Compare robots",
  },
  links: {
    robotCatalog: "Robot catalog",
    exploreMore: "Explore more",
    featuredRobot: "Featured robot",
    compareSideBySide: "Compare side by side",
    relatedRobots: "Related robots",
    moreOnSite: "More on HomeBotRadar",
  },
} as const;
