export const uiCopy = {
  nav: {
    commandCenter: "Command Center",
    robots: "Robots",
    compare: "Compare",
    radarFeed: "Radar Feed",
    news: "News",
    robotMatchmaker: "Robot Matchmaker",
  },
  navIcons: {
    commandCenter: "⌂",
    robots: "◉",
    compare: "✣",
    radarFeed: "◎",
    news: "✎",
    robotMatchmaker: "◈",
  },
  sidebar: {
    freshnessScore: "Data Freshness",
    lastSignal: "Last Signal",
  },
  homepage: {
    commandCenter: "Command Center",
    newsEyebrow: "News",
    latestRobotNews: "Latest Robot News",
    radarFeedEyebrow: "Radar Feed",
    latestRobotUpdates: "Latest Robot Updates",
    stayOnRadar: "Stay on Radar",
    viewFullProfile: "View Full Profile",
  },
  robot: {
    tabs: {
      overview: "Overview",
      capabilities: "Capabilities",
      techSpecs: "Tech Specs",
      ecosystem: "Ecosystem",
      availability: "Availability",
      signalHistory: "Signal History",
      fieldReports: "Reviews",
    },
    trackRobot: "Track Robot",
    tracking: "Tracking",
    addToCompare: "Add to Compare",
    inCompare: "In Compare",
    relatedRobots: "Related Robots",
    robotSignals: "Robot Signals",
    news: "News",
  },
  scores: {
    readinessScore: "Readiness Score",
    realityScore: "Reality Score",
    marketStatus: "Market Status",
    freshnessScore: "Data Freshness",
    confidenceScore: "Confidence Score",
    lastSignal: "Last Signal",
  },
  comments: {
    heading: "Comments",
    submitLabel: "Post comment",
    noCommentsYet: "No comments yet",
    commentCount: (count: number) =>
      `${count} comment${count === 1 ? "" : "s"}`,
    fieldReports: "Field Reports",
    communityReports: "Community Reports",
    submitFieldReport: "Submit Field Report",
    noFieldReportsYet: "No field reports yet",
    reportCount: (count: number) =>
      `${count} report${count === 1 ? "" : "s"}`,
    emptyPrompt: "Be the first to share a question or hands-on note.",
  },
  updates: {
    pageTitle: "Robot Updates",
    readUpdate: "Read update",
    readStory: "Read story",
    viewAll: "View all",
    noUpdatesYet: "No updates yet.",
    noNewsYet: "No news yet.",
    noDataUpdatesForRobot: "No data updates for this robot.",
    noNewsForRobot: "No news for this robot.",
  },
  compare: {
    eyebrow: "Compare",
  },
  search: {
    ariaLabel: "Search robots, news, and radar feed",
    sectionNewsAndRadar: "News & Radar Feed",
    compareRobots: "Compare robots",
  },
  links: {
    robotCatalog: "Robot catalog",
    exploreMore: "Explore more",
  },
} as const;
