export const uiCopy = {
  nav: {
    commandCenter: "Command Center",
    robots: "Robots",
    compare: "Compare",
    radarFeed: "Radar Feed",
    news: "News",
    robotMatchmaker: "Robot Matchmaker",
  },
  navIcons: {
    commandCenter: "⌂",
    robots: "◉",
    compare: "✣",
    radarFeed: "◎",
    news: "✎",
    robotMatchmaker: "◈",
    tracked: "♥",
  },
  /** Browse-by-mission hub icons — distinct from navIcons so cards read by task, not nav slot. */
  categoryMissionIcons: {
    humanoid: "⬭",
    homeAssistant: "⊞",
    elderCare: "⊚",
    conversation: "∿",
    zoomorphic: "⊙",
    desktop: "▭",
  },
  sidebar: {
    freshnessScore: "Data Freshness",
    lastSignal: "Last Signal",
  },
  homepage: {
    commandCenter: "Command Center",
    newsEyebrow: "News",
    latestRobotNews: "Latest Robot News",
    radarFeedEyebrow: "Radar Feed",
    latestRobotUpdates: "Latest Robot Updates",
    stayOnRadar: "Stay on Radar",
    viewFullProfile: "View Full Profile",
    dashboard: {
      browseByMission: "Browse by mission",
      popularToday: "Popular today",
      latestAdded: "Latest added robots",
      latestComments: "Latest comments",
      openFullMatrix: "Open full matrix",
      noCommentsYet:
        "No recent comments yet. Be the first to share your thoughts on a robot profile.",
      browseRobots: "Browse robots",
      unitsTracked: (count: number) => `${count} units tracked`,
      addedOn: "Added",
      onRobot: "on",
      onStory: "on story",
    },
    socialFeed: {
      eyebrow: "On X",
      heading: "Social feed",
      viewAll: "View all feeds",
      viewRobot: "View robot",
      readStory: "Read story",
      compare: "Compare",
      openPost: "Open on X",
      loadingPost: "Loading post…",
      footerNote:
        "Posts load from X when cards scroll into view. Robot and story links below each post are on HomeBotRadar.",
      pageTitle: "Social feed on X",
      pageLead:
        "Hand-picked posts from robot makers on X, with video. Each card links to robot profiles, news, and compare on HomeBotRadar.",
      subscribeEyebrow: "Also subscribe",
      subscribeLead:
        "X cards stay on this page. For article RSS, use News and Radar Feed:",
      newsRss: "News RSS",
      updatesRss: "Radar Feed RSS",
      browseNews: "Browse news",
      browseUpdates: "Browse Radar Feed",
    },
  },
  matrix: {
    showDiscontinued: "Show discontinued robots",
    showBuyNowOnly: "For sale only",
    windowEyebrow: "Matrix scan",
    prevWindow: "Prev scan",
    nextWindow: "Next scan",
    unitsRange: (start: number, end: number, total: number) =>
      `Units ${String(start).padStart(2, "0")}–${String(end).padStart(2, "0")} of ${total}`,
    windowLabel: (page: number, pageCount: number) =>
      `Scan ${String(page).padStart(2, "0")}/${String(pageCount).padStart(2, "0")}`,
  },
  robot: {
    tabs: {
      overview: "Overview",
      capabilities: "Capabilities",
      techSpecs: "Tech Specs",
      ecosystem: "Ecosystem",
      availability: "Availability",
      signalHistory: "Signal History",
      fieldReports: "Reviews",
    },
    trackRobot: "Track Robot",
    tracking: "Tracking",
    addToCompare: "Add to Compare",
    inCompare: "In Compare",
    relatedRobots: "Related Robots",
    robotSignals: "Robot Signals",
    news: "News",
  },
  scores: {
    readinessScore: "Readiness Score",
    readinessScoreHint:
      "How close this robot is to practical home use, based on specs, demos, and buy signals we track.",
    realityScore: "Reality Score",
    realityScoreHint:
      "How verified the robot is in the real world — shipping, pilots, and public proof.",
    marketStatus: "Market Status",
    freshnessScore: "Data Freshness",
    confidenceScore: "Confidence Score",
    lastSignal: "Last Signal",
  },
  comments: {
    submitLabel: "Post comment",
    submitFieldReport: "Submit Field Report",
    emptyPrompt: "Be the first to share a question or hands-on note.",
    usernamePlaceholder: "How should your name appear?",
  },
  updates: {
    pageTitle: "Robot Updates",
    readUpdate: "Read update",
    readStory: "Read story",
    viewAll: "View all",
    noUpdatesYet: "No updates yet.",
    noNewsYet: "No news yet.",
    noDataUpdatesForRobot: "No data updates for this robot.",
    noNewsForRobot: "No news for this robot.",
  },
  compare: {
    eyebrow: "Compare",
    sections: {
      performance: "Performance",
      specs: "Specs",
      availability: "Availability",
      intelligence: "Intelligence",
    },
    verdict: {
      title: "Quick verdict",
      headline: (leader: string, wins: number, total: number) =>
        `${leader} leads on ${wins} of ${total} comparable rows`,
      noComparableRows: "No clear leader on comparable numeric rows in this matchup.",
      leadsBadge: (count: number) => `Leads ${count}`,
    },
    chooseGuide: {
      title: "Who should choose which?",
      choosePrefix: "Choose",
      chooseSuffix: "if…",
      scoreboardEyebrow: "Scoreboard",
      winsLine: (count: number) => `wins ${count}`,
    },
    table: {
      specColumn: "Spec",
      footer: (count: number) =>
        `Green cells mark the stronger value in each row across ${count} robots.`,
    },
  },
  tracked: {
    eyebrow: "Tracked",
    pageTitle: "Your tracked robots",
    pageLead:
      "Robots you mark with Track Robot on any profile. Saved in this browser only.",
    emptyTitle: "No robots on your radar yet",
    emptyLead:
      "Open any robot profile and tap Track Robot. Your list stays on this device.",
    browseRobots: "Browse robots",
    clearAll: "Clear all",
    localNote:
      "Tracked robots are stored locally in your browser. Clearing site data removes them.",
    viewProfile: "View profile",
    untrack: "Untrack",
  },
  search: {
    ariaLabel: "Search robots, news, and radar feed",
    sectionNewsAndRadar: "News & Radar Feed",
    compareRobots: "Compare robots",
    trackedRobots: "Tracked robots",
  },
  links: {
    robotCatalog: "Robot catalog",
    exploreMore: "Explore more",
    featuredRobot: "Featured robot",
    compareSideBySide: "Compare side by side",
    relatedRobots: "Related robots",
    moreOnSite: "More on HomeBotRadar",
  },
} as const;
